'use strict'

const re = require('./')

for (let i = 0; i < 1000000; i++) {
  re.test('a.net')
  re.test('aa.net')
  re.test('x.com')
  re.test('0-0O.COM')
  re.test('0-OZ.CO.uk')
  re.test('www.my---domain.com')
  re.test('xn--unnebck-9wa.se')
  re.test('0-TENSION.COM.br')
  re.test('0-WH-AO14-0.COM-com.net')
  re.test('a-1234567890-1234567890-1234567890-1234567890-1234567890-1234-z.eu.us')
  re.test('www.google.com')
  re.test('google.com')
  re.test('test123.com')
  re.test('test-info.com')
  re.test('sub.test.com')
  re.test('sub.test-info.com')
  re.test('test.com.au')
  re.test('test.tld1')
  re.test('test.0-1')
  re.test('g.co')
  re.test('co.uk')
  re.test('test.t.t.c')
  re.test('test.t.t.co')
  re.test('test.xn--xkc2al3hye2a')
  re.test('tedjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhaddjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhadjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhaddjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhadsjfasd.fhsadjfsdhf.asst.com')
  re.test('.com')
  re.test('com.')
  re.test('com')
  re.test('com.')
  re.test('test.com.')
  re.test('test.x.com.')
  re.test('0-0O_.COM')
  re.test('test,com')
  re.test('test.⏰.com')
  re.test('test.com/users')
  re.test('-0-0O.COM')
  re.test('-a.dot')
  re.test('-test.com')
  re.test('sub.-test.com')
  re.test('sub.test-.com')
  re.test('test-.com')
  re.test('test.-com')
  re.test('test.com-')
  re.test('test.123')
  re.test('a-1234567890-1234567890-1234567890-1234567890-1234567890-12345-z.eu.us')
  re.test('tedjagkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhaddjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhadjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhaddjgkghdfs.fgahfdsjfh.asfha.jsdhfksdfhsdjfhkasd.fhasdjfkhadsjfasd.fhsadjfsdhf.asst.com')
}
